### ISSUE TITLE
v1.7-rc agent crashed

### ISSUE THREAD

**Issue by buckxu** [bytedance/Elkeid#141]
## Describe the bug
just left agent running two days, it suddenly crashed!
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8f463d]

goroutine 7 [running]:
github.com/bytedance/Elkeid/agent/resource.GetDirSize.func1({0xc000647a00, 0x74}, {0x0, 0x0}, {0xc0000b1cd8, 0x0})
	/home/buckxu/code/Elkeid/agent/resource/resource.go:59 +0x3d
path/filepath.walk({0xc0001b1c70, 0x4b}, {0xb28648, 0xc0002260d0}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:438 +0x20d
path/filepath.walk({0xc0001b1a90, 0x43}, {0xb28648, 0xc0001f5ee0}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc0000cc500, 0x3c}, {0xb28648, 0xc0001f5ba0}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc00056e2a0, 0x23}, {0xb28648, 0xc0001f5a00}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc000384640, 0x1b}, {0xb28648, 0xc0001f5930}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc000379218, 0x13}, {0xb28648, 0xc0003a8750}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.walk({0xc00009b7c4, 0xc}, {0xb28648, 0xc0003a8270}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:442 +0x28f
path/filepath.Walk({0xc00009b7c4, 0xc}, 0xc0000b1cd8)
	/usr/local/go/src/path/filepath/path.go:505 +0x6c
github.com/bytedance/Elkeid/agent/resource.GetDirSize({0xc00009b7c4, 0xc000095aa0}, {0xa50b05, 0x6})
	/home/buckxu/code/Elkeid/agent/resource/resource.go:68 +0x5d
github.com/bytedance/Elkeid/agent/heartbeat.getAgentStat({0xc0000b1f78, 0xc0000b1f18, 0xf28b40})
	/home/buckxu/code/Elkeid/agent/heartbeat/heartbeat.go:61 +0xb91
github.com/bytedance/Elkeid/agent/heartbeat.Startup({0xb224e8, 0xc0000d37c0}, 0x0)
	/home/buckxu/code/Elkeid/agent/heartbeat/heartbeat.go:131 +0x185
created by main.main
	/home/buckxu/code/Elkeid/agent/main.go:89 +0x10cf
```
**Related code**
```
 56 func GetDirSize(path string, except string) uint64 {
 57     var dirSize uint64 = 0
 58     readSize := func(path string, file os.FileInfo, err error) error {
 59         if !file.IsDir() {
 60             dirSize += uint64(file.Size())
 61         } else {
 62             if file.Name() == except {
 63                 return filepath.SkipDir
 64             }
 65         }
 66         return nil
 67     }
 68     filepath.Walk(path, readSize)
 69     return dirSize
 70 }
```
It appears that parameter *file* is not checked against *nil*

## To Reproduce
no

## Expected behavior
no

## Screenshots

##OS information (please complete the following information):
 - Distribution: Ubuntu
 - Version 18.04.1
 - Kernel info e.g. 5.4.0-89-generic

## Hardware info (if you think it's helpful)
 **VMWare**

## Additional context
No

**Comment by Serinalice** [comment]
Has been fixed by 84beef247306bee6d9efeb5f51ea89eadc2da60b.
