### ISSUE TITLE
docker启动kafka 镜像异常重启

### ISSUE THREAD

**Issue by jgbooks** [bytedance/Elkeid#153]
@xie4ever 遇到过吗？
docker版本按照教程跑起来遇到如下问题
` ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentClusterIdException: The Cluster ID XvvBW_j6TTCf5T8eS8HDfA doesn't match stored clusterId Some(0HnAgz-oTY6FLjz4EeUdEw) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
        at kafka.server.KafkaServer.startup(KafkaServer.scala:223)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
`

_Originally posted by @jgbooks in https://github.com/bytedance/Elkeid/issues/68#issuecomment-999525242_

**Comment by jgbooks** [comment]
'bitnami/kafka:latest' 存在问题，替换其他镜像测试正常
