### ISSUE TITLE
加载Modify插件报错

### ISSUE THREAD

**Issue by bigbrobro** [bytedance/Elkeid#275]
### 描述
Hub加载Modify插件报错，插件是作为告警压制使用，使用内置的cacheout库实现告警压制功能，但是加载插件后 plugin.stdout 出现错误情况

### plugin.stdout 报错详情
```
- - - [2022-08-09 15:29:59] "GET /reload HTTP/1.1" 200 862 0.002285
- - - [2022-08-09 15:29:59] "GET /reload HTTP/1.1" 200 862 0.003835
Traceback (most recent call last):
  File "/elkeid/hub/py/pypy/site-packages/gevent/libev/corecffi.py", line 61, in python_prepare_callback
    AbstractCallbacks.python_prepare_callback(self, watcher_ptr)
  File "/elkeid/hub/py/pypy/site-packages/gevent/_ffi/loop.py", line 302, in python_prepare_callback
    loop._run_callbacks()
  File "/elkeid/hub/py/pypy/site-packages/gevent/_ffi/loop.py", line 489, in _run_callbacks
    while self._callbacks:
KeyboardInterrupt
2022-08-09T15:36:44Z
Traceback (most recent call last):
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib-python/3/runpy.py", line 196, in _run_module_as_main
    "__main__", mod_spec)
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/elkeid/hub/py/pypy/site-packages/gevent/monkey.py", line 1375, in <module>
    main()
  File "/elkeid/hub/py/pypy/site-packages/gevent/monkey.py", line 1336, in main
    return run_meth(sys.argv[0], run_name='__main__')
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib-python/3/runpy.py", line 266, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib-python/3/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "start.py", line 520, in <module>
    gevent.joinall(segJvlkEGVPQtNMVnhSNWbzVfkBHzWnmniAAbbZWwPweUsXvSRJIeADVULGmMTJKIgpQFQnfOCVMiLiJOwDfmPDZFshzwRZShdXaWtrtYoDKGcrvOcABVErtwkEhaVng)
  File "/elkeid/hub/py/pypy/site-packages/gevent/greenlet.py", line 1067, in joinall
    return wait(greenlets, timeout=timeout, count=count)
  File "/elkeid/hub/py/pypy/site-packages/gevent/_hub_primitives.py", line 287, in wait_on_objects
    return list(iwait_on_objects(objects, timeout, count))
  File "/elkeid/hub/py/pypy/site-packages/gevent/_hub_primitives.py", line 176, in __next__
    item = self._waiter.get()
  File "/elkeid/hub/py/pypy/site-packages/gevent/_waiter.py", line 195, in get
    Waiter.get(self)
  File "/elkeid/hub/py/pypy/site-packages/gevent/_waiter.py", line 154, in get
    return self.hub.switch()
  File "/elkeid/hub/py/pypy/site-packages/gevent/_greenlet_primitives.py", line 65, in switch
    return _greenlet_switch(self) # pylint:disable=undefined-variable
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib_pypy/greenlet.py", line 61, in switch
    return self.__switch('switch', (args, kwds))
  File "/elkeid/hub/py/pypy3.7-v7.3.5-linux64/lib_pypy/greenlet.py", line 115, in __switch
    args, kwds = unbound_method(current, *baseargs, to=target)
  File "/elkeid/hub/py/pypy/site-packages/gevent/libev/corecffi.py", line 61, in python_prepare_callback
    AbstractCallbacks.python_prepare_callback(self, watcher_ptr)
  File "/elkeid/hub/py/pypy/site-packages/gevent/_ffi/loop.py", line 302, in python_prepare_callback
    loop._run_callbacks()
  File "/elkeid/hub/py/pypy/site-packages/gevent/_ffi/loop.py", line 489, in _run_callbacks
    while self._callbacks:
KeyboardInterrupt
generating ./_elkeid_queue.c
(already up-to-date)
the current directory is '/elkeid/hub/py'
running build_ext
building '_elkeid_queue' extension
gcc -pthread -DNDEBUG -O2 -fPIC -I. -I/elkeid/hub/py/pypy/include -I/elkeid/hub/py/pypy3.7-v7.3.5-linux64/include -c _elkeid_queue.c -o ./_elkeid_queue.o -std=c99
gcc -pthread -shared ./_elkeid_queue.o -lm -lrt -o ./_elkeid_queue.pypy37-pp73-x86_64-linux-gnu.so
INFO:root:use plugin dir: /elkeid/hub/config/plugin
INFO:root:zip_dir:/elkeid/hub/py/plugin_zip
INFO:root:unzip_dir:/elkeid/hub/py/plugin_unzip
INFO:root:load local plugin: /elkeid/hub/config/plugin/CompressAlert
INFO:root:load local plugin: /elkeid/hub/config/plugin/DNSptr
INFO:root:load local plugin: /elkeid/hub/config/plugin/SendToWeCom
INFO:root:load local plugin: /elkeid/hub/config/plugin/SendToDingding
INFO:root:load local plugin: /elkeid/hub/config/plugin/SendToLarkGroup
INFO:root:load local plugin: /elkeid/hub/config/plugin/SendToTelegram
INFO:root:load local plugin: /elkeid/hub/config/plugin/SendToLark
INFO:root:{"Modify:CompressAlert": {"key": "Modify:CompressAlert", "name": "CompressAlert", "type": "Modify", "err": ""}, "Append:DNSptr": {"key": "Append:DNSptr", "name": "DNSptr", "type": "Append", "err": ""}, "Action:SendToWeCom": {"key": "Action:SendToWeCom", "name": "SendToWeCom", "type": "Action", "err": ""}, "Action:SendToDingding": {"key": "Action:SendToDingding", "name": "SendToDingding", "type": "Action", "err": ""}, "Action:SendToLarkGroup": {"key": "Action:SendToLarkGroup", "name": "SendToLarkGroup", "type": "Action", "err": ""}, "Action:SendToTelegram": {"key": "Action:SendToTelegram", "name": "SendToTelegram", "type": "Action", "err": ""}, "Action:SendToLark": {"key": "Action:SendToLark", "name": "SendToLark", "type": "Action", "err": ""}}
INFO:root:{'Modify:CompressAlert': <bound method Plugin.plugin_exec of <CompressAlert.plugin.Plugin object at 0x0000000002a55b78>>, 'Append:DNSptr': <bound method Plugin.plugin_exec of <DNSptr.plugin.Plugin object at 0x0000000002f83e50>>, 'Action:SendToWeCom': <bound method Plugin.plugin_exec of <SendToWeCom.plugin.Plugin object at 0x000000000304a800>>, 'Action:SendToDingding': <bound method Plugin.plugin_exec of <SendToDingding.plugin.Plugin object at 0x000000000304a4f0>>, 'Action:SendToLarkGroup': <bound method Plugin.plugin_exec of <SendToLarkGroup.plugin.Plugin object at 0x000000000304a1a8>>, 'Action:SendToTelegram': <bound method Plugin.plugin_exec of <SendToTelegram.plugin.Plugin object at 0x000000000304aec8>>, 'Action:SendToLark': <bound method Plugin.plugin_exec of <SendToLark.plugin.Plugin object at 0x000000000304af00>>}
INFO:root:{"Modify:CompressAlert": {"key": "Modify:CompressAlert", "name": "CompressAlert", "type": "Modify", "err": ""}, "Append:DNSptr": {"key": "Append:DNSptr", "name": "DNSptr", "type": "Append", "err": ""}, "Action:SendToWeCom": {"key": "Action:SendToWeCom", "name": "SendToWeCom", "type": "Action", "err": ""}, "Action:SendToDingding": {"key": "Action:SendToDingding", "name": "SendToDingding", "type": "Action", "err": ""}, "Action:SendToLarkGroup": {"key": "Action:SendToLarkGroup", "name": "SendToLarkGroup", "type": "Action", "err": ""}, "Action:SendToTelegram": {"key": "Action:SendToTelegram", "name": "SendToTelegram", "type": "Action", "err": ""}, "Action:SendToLark": {"key": "Action:SendToLark", "name": "SendToLark", "type": "Action", "err": ""}}
INFO:root:{"Modify:CompressAlert": {"key": "Modify:CompressAlert", "name": "CompressAlert", "type": "Modify", "err": ""}, "Append:DNSptr": {"key": "Append:DNSptr", "name": "DNSptr", "type": "Append", "err": ""}, "Action:SendToWeCom": {"key": "Action:SendToWeCom", "name": "SendToWeCom", "type": "Action", "err": ""}, "Action:SendToDingding": {"key": "Action:SendToDingding", "name": "SendToDingding", "type": "Action", "err": ""}, "Action:SendToLarkGroup": {"key": "Action:SendToLarkGroup", "name": "SendToLarkGroup", "type": "Action", "err": ""}, "Action:SendToTelegram": {"key": "Action:SendToTelegram", "name": "SendToTelegram", "type": "Action", "err": ""}, "Action:SendToLark": {"key": "Action:SendToLark", "name": "SendToLark", "type": "Action", "err": ""}}
```

### ruleset
```
<rule rule_id="rule_test_detect" author="Elkeid" type="Detection">
        <rule_name>rule_test_detect</rule_name>
        <alert_data>True</alert_data>
        <harm_level>high</harm_level>
        <desc kill_chain_id="evasion" affected_target="host_process">rule_test</desc>
        <filter part="data_type">59</filter>
        <check_list>
                <check_node type="INCL" part="exe">/bin/id</check_node>
        </check_list>
        <node_designate></node_designate>
        <del />
        <action />
        <modify>CompressAlert</modify>
        <append type="static" append_field_name="alert_type_us">evasion</append>
        <append type="static" append_field_name="compress_flag">nodename_argv</append>
        <append type="static" append_field_name="rule_name">rule_test_detect</append>
    </rule>
```

### 插件代码

```
from cacheout import LRUCache

class Plugin(object):
    def __init__(self):
        self.name = None
        self.type = None
        self.log = None
        self.redis = None
        self.cache = LRUCache(maxsize=1024 * 1024)

    def plugin_exec(self, arg, config):
        result = dict()
        '''
        "compress_flag": "nodename_argv"
        '''
        cache_key = "{}_{}".format(arg['SMITH_INPUT'], arg['SMITH_KEY'])
        result["flag"] = False
        result["msg"] = ""

        if "compress_flag" in arg.keys():
            key_list = arg.get('compress_flag').split("_")
            cache_key = "_".join([arg[k] for k in key_list])

        cache_result = self.cache.get(cache_key)
        if cache_result is None:
            self.cache.set(cache_key, arg, ttl=60)
            result["flag"] = True
            result["msg"] = arg
            self.log.info(result)
            return result
        self.log.info(result)
        return result
```

**Comment by TaeRoen** [comment]
plugin.stdout里的两次退出都是KeyboardInterrupt，是在命令行里 ctrl-c了hub后，python plugin进程也收到ctrl-c后抛出的，和modify plugin无关。plugin.stdout里还有其他modify plugin有关的错误吗？

**Comment by bigbrobro** [comment]
如交流群沟通，hub实例中只有一个modify插件，hub使用nohup方式在后台运行，报错只有plugin.stdout出现，其他hub日志没有看到记录

**Comment by TaeRoen** [comment]
plugin.stdout 是连续的吧，看样子是python进程一直在重启。目前是python进程在一直重启，还是hub带着python进程在一直重启？目前是hub的pid一直不变，但是python的进程pid一直变吗？

**Comment by TaeRoen** [comment]
所有plugin的__init__()里面，有没有特别耗时的逻辑？

**Comment by bigbrobro** [comment]
发现hub也退出
```
root@ip-10-20-10-103:/elkeid/hub# ./bootstrap.sh
[AgentSmith] SMITH START



wait for plugin init
[AgentSmith] SMITH 'elkeid_hids_alarm' PROJECT READY TO START
[AgentSmith] SMITH 'asset_to_manager' PROJECT READY TO START
Run Input
Run Input



UpdateManagerToken success
UpdateManagerToken Token Init Success eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJleHAiOjE2NjAxMDcxODZ9.kNMuA1UnD4QGMEkiaOfoY7yjGoN74C-Y1yhICPk1Zc4
panic: interface conversion: interface {} is uint64, not int64

goroutine 146 [running]:
code.byted.org/security/AgentSmith-HUB/src/output.(*Output).OutputDataProc��1�code.byted.org/security/AgentSmith-HUB/src/common.MapToJson(0xc013df0240, 0xc017e328d0, 0x0, 0x0)
        ?:148 +0x445
1.1(0xc013df0240, 0xc0134833b0, 0x45, 0xc013dea930, 0xc013db5e00)
        ?:198 +0xd9
root@ip-10-20-10-103:/elkeid/hub# 
```

**Comment by bigbrobro** [comment]
> plugin.stdout 是连续的吧，看样子是python进程一直在重启。目前是python进程在一直重启，还是hub带着python进程在一直重启？目前是hub的pid一直不变，但是python的进程pid一直变吗？

不止python pid在变，hub也变
<img width="954" alt="image" src="https://user-images.githubusercontent.com/44428568/183800375-589b7af0-ab94-450f-9f39-2233d0bb4632.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/44428568/183800401-8e39df60-609e-4a0c-b573-7f088515bd62.png">

**Comment by bigbrobro** [comment]
> 所有plugin的__init__()里面，有没有特别耗时的逻辑？

插件代码
```
from cacheout import LRUCache

class Plugin(object):
    def __init__(self):
        self.name = None
        self.type = None
        self.log = None
        self.redis = None
        self.cache = LRUCache(maxsize=1024 * 1024)

    def plugin_exec(self, arg, config):
        result = dict()
        '''
        "compress_flag": "nodename_argv"
        '''
        cache_key = "{}_{}".format(arg['SMITH_INPUT'], arg['SMITH_KEY'])
        result["flag"] = False
        result["msg"] = ""

        if "compress_flag" in arg.keys():
            key_list = arg.get('compress_flag').split("_")
            cache_key = "_".join([arg[k] for k in key_list])

        cache_result = self.cache.get(cache_key)
        if cache_result is None:
            self.cache.set(cache_key, arg, ttl=60)
            result["flag"] = True
            result["msg"] = arg
            self.log.info(result)
            return result
        self.log.info(result)
        return result
```

**Comment by TaeRoen** [comment]
应该是hub启动时退出导致的，我们先分析下什么情况会导致这个退出

**Comment by bigbrobro** [comment]
> > plugin.stdout 是连续的吧，看样子是python进程一直在重启。目前是python进程在一直重启，还是hub带着python进程在一直重启？目前是hub的pid一直不变，但是python的进程pid一直变吗？
> 
> 不止python pid在变，hub也变 <img alt="image" width="954" src="https://user-images.githubusercontent.com/44428568/183800375-589b7af0-ab94-450f-9f39-2233d0bb4632.png"> <img alt="image" width="904" src="https://user-images.githubusercontent.com/44428568/183800401-8e39df60-609e-4a0c-b573-7f088515bd62.png">

是我测试的问题，报错后hub应该是直接退出了，hub使用服务的方式在运行，报错退出后会重新启动，所以会循环报错

**Comment by TaeRoen** [comment]
我们怀疑是这个问题：
map在golang里通过msgpack序列化反序列化到python，再从python里通过msgpack序列化反序列到golang，int64类型变成了uint64，所以导致了hub的退出，预期下午我们会新发布一个版本来fix。

**Comment by bigbrobro** [comment]
> 我们怀疑是这个问题： map在golang里通过msgpack序列化反序列化到python，再从python里通过msgpack序列化反序列到golang，int64类型变成了uint64，所以导致了hub的退出，预期下午我们会新发布一个版本来fix。

收到，是否hub端口自定义失效一起更新，哈哈哈哈哈哈哈，期待
