### ISSUE TITLE
按照官方教程，通过manager下发driver插件后，driver插件跑不起来

### ISSUE THREAD

**Issue by xie4ever** [bytedance/Elkeid#68]
只有driver插件跑不起来，journal和collector都可以正常运行。

driver访问的几个地址都是404，driver日志如下：

```
[2021-07-06 00:21:56.315173 -07:00] INFO [driver] src/main.rs:32: Crash check passed
[2021-07-06 00:21:56.316982 -07:00] INFO [driver] src/main.rs:40: Kernel version check passed
[2021-07-06 00:21:56.339276 -07:00] INFO [driver::prepare] src/prepare.rs:145: Downloading ko from https://lf3-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.ko
[2021-07-06 00:21:56.339337 -07:00] INFO [driver::prepare] src/prepare.rs:23: Downloading checksum from https://lf3-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.sha256
[[1;38;5;208m2021-07-06 00:21:58.107840 -07:00[0m] [1;38;5;208mWARN[0m [driver::prepare] src/prepare.rs:148: [1;38;5;208mHTTP status client error (404 Not Found) for url (https://lf3-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic.sha256)[0m
[2021-07-06 00:21:58.107917 -07:00] INFO [driver::prepare] src/prepare.rs:145: Downloading ko from https://lf6-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.ko
[2021-07-06 00:21:58.107936 -07:00] INFO [driver::prepare] src/prepare.rs:23: Downloading checksum from https://lf6-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.sha256
[[1;38;5;208m2021-07-06 00:22:01.692868 -07:00[0m] [1;38;5;208mWARN[0m [driver::prepare] src/prepare.rs:148: [1;38;5;208mHTTP status client error (404 Not Found) for url (https://lf6-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic.sha256)[0m
[2021-07-06 00:22:01.692950 -07:00] INFO [driver::prepare] src/prepare.rs:145: Downloading ko from https://lf9-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.ko
[2021-07-06 00:22:01.692975 -07:00] INFO [driver::prepare] src/prepare.rs:23: Downloading checksum from https://lf9-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.sha256
[[1;38;5;208m2021-07-06 00:22:02.482479 -07:00[0m] [1;38;5;208mWARN[0m [driver::prepare] src/prepare.rs:148: [1;38;5;208mHTTP status client error (404 Not Found) for url (https://lf9-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic.sha256)[0m
[2021-07-06 00:22:02.482631 -07:00] INFO [driver::prepare] src/prepare.rs:145: Downloading ko from https://lf26-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.ko
[2021-07-06 00:22:02.482655 -07:00] INFO [driver::prepare] src/prepare.rs:23: Downloading checksum from https://lf26-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic
.sha256
[[1;38;5;208m2021-07-06 00:22:03.197481 -07:00[0m] [1;38;5;208mWARN[0m [driver::prepare] src/prepare.rs:148: [1;38;5;208mHTTP status client error (404 Not Found) for url (https://lf26-elkeid.bytetos.com/obj/elkeid-download/ko/hids_driver_1.6.0.0_5.4.0-77-generic.sha256)[0m
[[1;38;5;196m2021-07-06 00:22:03.197615 -07:00[0m] [1;38;5;196mERROR[0m [driver] src/main.rs:43: [1;38;5;196mCouldn't download ko[0m
```

agent日志如下：

```
2021-07-06T00:21:50.934-0700	INFO	transport/client.go:69	Config:<Name:"driver" Version:"1.6.0.0" SHA256:"a9ab7a2eda69b83d830a6061a393f886a7b125ea63e7ae1df4a276105764b37d" DownloadURL:"https://lf3-elkeid.bytetos.com/obj/elkeid-download/plugin/driver/driver_1.6.0.0_amd64.plg" DownloadURL:"https://lf6-elkeid.bytetos.com/obj/elkeid-download/plugin/driver/driver_1.6.0.0_amd64.plg" DownloadURL:"https://lf9-elkeid.bytetos.com/obj/elkeid-download/plugin/driver/driver_1.6.0.0_amd64.plg" DownloadURL:"https://lf26-elkeid.bytetos.com/obj/elkeid-download/plugin/driver/driver_1.6.0.0_amd64.plg" > Config:<Name:"journal_watcher" Version:"1.6.0.0" SHA256:"a0c065514debf6f2109aa873ece86ec89b0e6ccedfa05c124b5863a4568ee20c" DownloadURL:"https://lf3-elkeid.bytetos.com/obj/elkeid-download/plugin/journal_watcher/journal_watcher_1.6.0.0_amd64.plg" DownloadURL:"https://lf6-elkeid.bytetos.com/obj/elkeid-download/plugin/journal_watcher/journal_watcher_1.6.0.0_amd64.plg" DownloadURL:"https://lf9-elkeid.bytetos.com/obj/elkeid-download/plugin/journal_watcher/journal_watcher_1.6.0.0_amd64.plg" DownloadURL:"https://lf26-elkeid.bytetos.com/obj/elkeid-download/plugin/journal_watcher/journal_watcher_1.6.0.0_amd64.plg" > Config:<Name:"collector" Version:"1.6.0.0" SHA256:"f6e0b34de998844cbfc95ae0e47d39225c2449833657a6a6289d9722d8e2fdc8" DownloadURL:"https://lf3-elkeid.bytetos.com/obj/elkeid-download/plugin/collector/collector_1.6.0.0_amd64.plg" DownloadURL:"https://lf6-elkeid.bytetos.com/obj/elkeid-download/plugin/collector/collector_1.6.0.0_amd64.plg" DownloadURL:"https://lf9-elkeid.bytetos.com/obj/elkeid-download/plugin/collector/collector_1.6.0.0_amd64.plg" DownloadURL:"https://lf26-elkeid.bytetos.com/obj/elkeid-download/plugin/collector/collector_1.6.0.0_amd64.plg" > 
2021-07-06T00:21:56.312-0700	INFO	plugin/plugin.go:162	Plugin work directory: /home/xie/path/src/Elkeid/agent/plugin/driver/
2021-07-06T00:21:56.314-0700	INFO	plugin/server.go:126	Received a registration:{Pid:37832 Name:driver Version:1.6.0.0}
2021-07-06T00:21:56.315-0700	INFO	plugin/server.go:141	Plugin has been successfully connected:&{name:driver version:1.6.0.0 checksum:a9ab7a2eda69b83d830a6061a393f886a7b125ea63e7ae1df4a276105764b37d cmd:0xc000252000 conn:0xc000010138 runtimePID:37832 pgid:37832 IO:0 CPU:0 reader:0xc000330880 exited:{Value:{v:false} _:[]} Counter:{_:[] v:0}}
2021-07-06T00:22:00.120-0700	INFO	plugin/plugin.go:162	Plugin work directory: /home/xie/path/src/Elkeid/agent/plugin/journal_watcher/
2021-07-06T00:22:00.122-0700	INFO	plugin/server.go:126	Received a registration:{Pid:37842 Name:journal_watcher Version:1.6.0.0}
2021-07-06T00:22:00.122-0700	INFO	plugin/server.go:141	Plugin has been successfully connected:&{name:journal_watcher version:1.6.0.0 checksum:a0c065514debf6f2109aa873ece86ec89b0e6ccedfa05c124b5863a4568ee20c cmd:0xc0000b1760 conn:0xc000010168 runtimePID:37842 pgid:37842 IO:0 CPU:0 reader:0xc000330960 exited:{Value:{v:false} _:[]} Counter:{_:[] v:0}}
2021-07-06T00:22:02.225-0700	INFO	plugin/plugin.go:162	Plugin work directory: /home/xie/path/src/Elkeid/agent/plugin/collector/
2021-07-06T00:22:02.231-0700	INFO	plugin/server.go:126	Received a registration:{Pid:37849 Name:collector Version:1.6.0.0}
2021-07-06T00:22:02.231-0700	INFO	plugin/server.go:141	Plugin has been successfully connected:&{name:collector version:1.6.0.0 checksum:f6e0b34de998844cbfc95ae0e47d39225c2449833657a6a6289d9722d8e2fdc8 cmd:0xc000252840 conn:0xc000010200 runtimePID:37849 pgid:37849 IO:0 CPU:0 reader:0xc000330a60 exited:{Value:{v:false} _:[]} Counter:{_:[] v:0}}
2021-07-06T00:22:03.325-0700	ERROR	plugin/server.go:147	EOF
```

**Comment by EBWi11** [comment]
目前我们提供的预编译的driver ko仅仅作为测试使用，仅覆盖了一部分社区版的centos/ubuntu，如果遇到找不到预编译ko的情况需要自行编译ko使用

**Comment by EBWi11** [comment]
我们会定期更新最新版本的Driver预编译ko，尽可能的覆盖全面。近期会更新目前不存在的5.4.0-77预编译ko

**Comment by jgbooks** [comment]
@xie4ever 遇到过吗？
docker版本按照教程跑起来遇到如下问题
` ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentClusterIdException: The Cluster ID XvvBW_j6TTCf5T8eS8HDfA doesn't match stored clusterId Some(0HnAgz-oTY6FLjz4EeUdEw) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
        at kafka.server.KafkaServer.startup(KafkaServer.scala:223)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
`
